version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env.local
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .next:/app/.next
    command: sh -c "./wait-for-db.sh npm run migrate && npm run dev"
    environment:
      - WATCHPACK_POLLING=true

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa2024
      POSTGRES_DB: my_next_app_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
